-- Apply ingredient smart defaults by name (works on any database regardless of UUIDs)
-- Replaces uuid-based migrations 000001 and 000002 which matched 0 rows on Neon

UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 10 WHERE "name" = 'Almond butter';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Almonds, raw';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Apple';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Asparagus, cooked';
UPDATE "ingredients" SET "default_unit" = 'tbsp', "default_quantity" = 1 WHERE "name" = 'Avocado oil';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 15 WHERE "name" = 'Avocado, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Bacon, cooked';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Balsamic vinegar';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Banana';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Basmati rice, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Beef sirloin, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Beef tenderloin, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Bell pepper, green';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Bell pepper, red';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Black beans, cooked';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Black pepper, ground';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Blueberries';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Broccoli, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Brown rice, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Bulgur wheat, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 10 WHERE "name" = 'Butter, unsalted';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Cabbage, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Carrots, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Casein protein powder';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Cashews, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Cauliflower, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Celery, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Cheddar cheese';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Cherry tomatoes';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Chia seeds';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Chicken breast, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Chicken thigh, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Chickpeas, cooked';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Coconut milk, canned';
UPDATE "ingredients" SET "default_unit" = 'tbsp', "default_quantity" = 1 WHERE "name" = 'Coconut oil';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Cod, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Corn, sweet, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Cottage cheese (1% fat)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Cottage cheese (4% fat)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Couscous, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Cream cheese';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Cucumber';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 15 WHERE "name" = 'Dark chocolate (70%+)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Dates, Medjool';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Dijon mustard';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Edamame, cooked';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Egg whites, cooked';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Egg, whole, cooked';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Eggplant, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Feta cheese';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Flax seeds, ground';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 5 WHERE "name" = 'Garlic, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Grapes';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Greek yogurt, full-fat';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Greek yogurt, non-fat';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Green beans, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Ground beef (80% lean)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Ground beef (90% lean)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Ground chicken';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Ground turkey (93% lean)';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Honey';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Hot sauce (generic)';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Hummus';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Kale, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Kidney beans, cooked';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Lemon juice';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Lentils, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Lettuce, romaine';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Mackerel, cooked';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Mango';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Maple syrup';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Mozzarella cheese';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Mushrooms, white, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Oatmeal, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Oats, rolled, dry';
UPDATE "ingredients" SET "default_unit" = 'tbsp', "default_quantity" = 1 WHERE "name" = 'Olive oil, extra virgin';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Onion, raw';
UPDATE "ingredients" SET "default_unit" = 'piece', "default_quantity" = 1 WHERE "name" = 'Orange';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Parmesan cheese';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Pasta, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 10 WHERE "name" = 'Peanut butter, natural';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Peanuts, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Peas, green, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Pineapple';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Pita bread, whole wheat';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Pork loin, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Pork tenderloin, cooked';
UPDATE "ingredients" SET "default_unit" = 'tbsp', "default_quantity" = 1 WHERE "name" = 'Potato, boiled';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Pumpkin seeds, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Quinoa, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Raisins';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Raspberries';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Ricotta cheese';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Salmon, Atlantic, cooked';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Salsa';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Salt';
UPDATE "ingredients" SET "default_unit" = 'tbsp', "default_quantity" = 1 WHERE "name" = 'Sardines, canned in oil';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Sea bass, cooked';
UPDATE "ingredients" SET "default_unit" = 'ml', "default_quantity" = 200 WHERE "name" = 'Semi-skimmed milk';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Shrimp, cooked';
UPDATE "ingredients" SET "default_unit" = 'ml', "default_quantity" = 200 WHERE "name" = 'Skimmed milk';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Sourdough bread';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Soy sauce';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Spinach, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Spinach, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Strawberries';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Sunflower seeds, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Sweet potato, baked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Tahini (sesame paste)';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Tempeh';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Tilapia, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Tofu, firm';
UPDATE "ingredients" SET "default_unit" = 'pinch', "default_quantity" = 1 WHERE "name" = 'Tomato paste';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Tomato, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Tortilla, corn';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Tortilla, flour';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Tuna, canned in water';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Turkey breast, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 20 WHERE "name" = 'Walnuts, raw';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 200 WHERE "name" = 'Watermelon';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 30 WHERE "name" = 'Whey protein powder';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'White beans, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'White bread';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'White rice, cooked';
UPDATE "ingredients" SET "default_unit" = 'ml', "default_quantity" = 200 WHERE "name" = 'Whole milk';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 80 WHERE "name" = 'Whole wheat bread';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 150 WHERE "name" = 'Whole wheat pasta, cooked';
UPDATE "ingredients" SET "default_unit" = 'g', "default_quantity" = 100 WHERE "name" = 'Zucchini, cooked';
